### ISSUE TITLE
error at addon activation

### ISSUE THREAD

**Issue by danieleart** [c30ra/uv-align-distribute#17]
Hello, i get this error when i try to activate the addon (note: i installed this by dragging the uv distribution folder directly into the "appdata > roaming > blender foundation > blender > 2.93 > scripts > addons" folder  , since using the install command from the addon panel in blender didn't seem to do anything for me.
thanks  for any help 

Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 2.93\2.93\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "C:\Users\Win10Pro\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\uv_align_distribute\__init__.py", line 62, in <module>
    from . import align_operations
  File "C:\Users\Win10Pro\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\uv_align_distribute\align_operations.py", line 23, in <module>
    from . import make_islands, operator_manager, templates, utils
  File "C:\Users\Win10Pro\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\uv_align_distribute\make_islands.py", line 22, in <module>
    from . import global_def, island, utils
  File "C:\Users\Win10Pro\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\uv_align_distribute\island.py", line 6, in <module>
    import networkx
ModuleNotFoundError: No module named 'networkx'

**Comment by c30ra** [comment]
there is something strange in the output: uv_align_distribute_init_.py this file doesn't exist...
you should have this directory tree

uv_align_distribute:.                             
            │   align_operations.py         
            │   distribution_operations.py  
            │   geometry.py                 
            │   global_def.py               
            │   install.py                  
            │   island.py                   
            │   make_islands.py             
            │   match_islands.py            
            │   operator_manager.py         
            │   pack_islands.py             
            │   snap_islands.py             
            │   templates.py                
            │   ui.py                       
            │   utils.py                    
            │   __init__.py                 

As you can see, there is only __init__.py, not uv_align_distribute_init_.py. Can you please check this?
Also, have you downloaded the zip from here?

Is everything is correct, then probably there is something wrong on installation of some modules.
