### ISSUE TITLE
Unable to install add-on on Blender 2.78c under linux.

### ISSUE THREAD

**Issue by M-Klekowicki** [c30ra/uv-align-distribute#9]
After choosing the zip file in preferences I am unable to trigger it on. When trying, I get this feedback:

Traceback (most recent call last):
  File "/home/---/.steam/steam/steamapps/common/Blender/2.78/scripts/modules/addon_utils.py", line 330, in enable
    mod = __import__(module_name)
  File "/home/---/.config/blender/2.78/scripts/addons/uv_align_distribute/__init__.py", line 42, in <module>
    from . import align_operations
  File "/home/---/.config/blender/2.78/scripts/addons/uv_align_distribute/align_operations.py", line 21, in <module>
    from . import make_islands, templates, utils, operator_manager
  File "/home/---/.config/blender/2.78/scripts/addons/uv_align_distribute/make_islands.py", line 22, in <module>
    from . import global_def, island, utils
  File "/home/---/.config/blender/2.78/scripts/addons/uv_align_distribute/island.py", line 18, in <module>
    import networkx
  File "/home/----/.config/blender/2.78/scripts/addons/uv_align_distribute/networkx/networkx/__init__.py", line 87, in <module>
    import networkx.readwrite
  File "/home/---/.config/blender/2.78/scripts/addons/uv_align_distribute/networkx/networkx/readwrite/__init__.py", line 14, in <module>
    from networkx.readwrite.gml import *
  File "/home/----/.config/blender/2.78/scripts/addons/uv_align_distribute/networkx/networkx/readwrite/gml.py", line 44, in <module>
    from lib2to3.pgen2.parse import ParseError
ImportError: No module named 'lib2to3'

**Comment by c30ra** [comment]
Unfortunately, this is a know issue on linux: The blender distribution is missing lib2to3 python module, since linux is not my primary os i don't know any easy fix..

**Comment by c30ra** [comment]
fixed
